### ISSUE TITLE
Review 2

### ISSUE THREAD

**Issue by vr8hub** [Survey0r/george-macdonald_unspoken-sermons#2]
I'm going to go ahead and give you these small things; there are a number of issues with the `<q>`s, but I won't have time to document everything until this weekend.

- [ ] When an entire blockquote is a foreign language, the tag goes on the blockquote, not the contents; [SEMoS 8.2.9.6](https://standardebooks.org/manual/1.8.1/single-page#8.2.9.6). Thus the Greek blockquote in the epigraph should have the tag on the blockquote. Don't forget the CSS mentioned there as well.
- [ ] Quite a bit of the epigraph CSS from [7.4.1](https://standardebooks.org/manual/1.8.1/single-page#7.4.1) is missing: the entire section header CSS, the citation CSS, and the last element of the full-page CSS.
- [ ] It was "three-book" I said wasn't needed in the short description. The fact it's a book is a given; as mentioned previously, "A set of interlocking …" is fine.

**Comment by Survey0r** [comment]
OK, the above-mentioned fixes have been made.

**Comment by Survey0r** [comment]
OK, I fixed the above-mentioned issues.

**Comment by vr8hub** [comment]
OK, sorry, this was an extremely busy week, and there was too much to cover in this to do it quickly.

Before I get into to the `q`s, you missed adding the CSS in 8.2.9.6 I mentioned above.

The 8.2 section on italics is there so we can first determine _whether_ something should be italicized according to SEMoS rules (not according to the source), and then choose the semantically correct option if it should be italicized. 98% of the time, italics are either emphasis (`<em>`) or semanticated italics (`<i>` with either a language or semantic tag or both). Occasionally we have unsemanticated italics (`<i>` by itself, e.g. for sounds, the 3-2 section I asked Alex about, etc.) The only "official" use (mentioned in SEMoS) of `<q>` is internal thoughts, but it can also be used when longer quotes are italicized in the source but not quoted, and they _can_ be italicized, per SEMoS.

I mentioned both of those things when I brought up `<q>`: 1) sometimes used for longer quotes, 2) that were not themselves quoted ("only italics"). Also, as with quote marks, `q` is only used for actual quotes. A number of the `q`s you added don't follow one or more of those.

- [ ] In ch. 2-3 as an example, the `<q>Cannot</q>` is not a quote; that is clearly emphasis.
- [ ] In the case of, e.g., the "will not" in ch. 2-3, e.g., it is a quote, but since he's contrasting it with "cannot," which isn't, then it probably makes more sense that it's emphasis in both cases—`<em>Will not</em>, did I say? <em>Cannot</em>, I say.` Yes, in this particular case, that's what was there before; and in this particular case, I didn't say change them. :) Same for the "hard" at the end of 2-1.
- [ ] Using `q` inside of quote marks is redundant—they're both doing the same thing, indicating the text is a quote. For example, the end of 2-4 has “to the end that they ought always to pray, _and not to faint_.” Since the whole phrase is in quotes, then `q` there doesn't make sense. The italics there are clearly emphasis.
- [ ] In something like the end of 2-2, we again wouldn't use a `<q>` within quotes, so either it's an unsemanticated italic exception to 8.2.1 (like the 3-2 section I asked Alex about), or it's emphasis.

So, all of the `q`s above and any others like them need to be cleaned up. That can be done either by rebasing the originals, or adding even more commits. Since there were so many commits doing this in the first place, I'd prefer to try the former. If it gets too difficult, we can always fall back to just adding more commits.

A reminder: BACKUP YOUR LOCAL REPOSITORY before doing anything. This time the rebases _are_ going to change things, so you always want to be able to get back to where you were if things go south.

There are a couple of things that might need to be done: changing a commit, or dropping one entirely. It's possible either could lead to merge conflicts, which would then have to be dealt with. Your commits related to this are so small, though, that I hope we'll avoid them.

If you don't remember what a particular commit does, you can use `git show --word-diff=color --unified=0 <commitID>` to show you what's in a particular commit ID. The `<commitID>` there is just a placeholder for the actual ID; you won't type the brackets.

We'll handle dropping a commit first, since it's easier. You follow the instructions before to the point where you're in vim with the list of commits. (Remember, you give rebase the commit id of the commit _before_ the commit you want to affect.) At that point previously, you changed "pick" to "reword." This time, you're going to change "pick" to "drop" and then exit and save as before. Instead of dropping you back into the editor with the commit message, this time it's just going to drop the commit and then roll the rest forward. If there are no merge commits, then you'll just see the "Successfully rebased…" message at the command line when it's done, and that's all there is to it. I tested this, e.g., with the change from `<em>` to`<q>` in chapter-2-3 (c49423a), and it worked great with no merge conflicts. If there are any others that just need to be dropped completely, then just do the same steps with those ID's, one at a time. (It is actually possible to drop multiple at once, but I want to keep this as simple as possible.)

Do all of those you have. Once they're done, we'll handle the ones that need to be changed.

**Comment by Survey0r** [comment]
OK, apologies, I'm still getting a handle on the italics stuff, and MacDonald uses a **massive** amount of italics. I think things are getting clearer for me now.

(Also, the CSS from 8.2.9.6 is already in local.css, lines 149-153, but let me know if there's still something missing.)

So I'll delete the commits that change things to < q > where it shouldn't be changed to that, and we'll go from there.

**Comment by vr8hub** [comment]
My apologies, I didn't see it—that CSS should be at the top under the other @namespace entry.

And no worries—you're correct, MacDonald loved his italics. :) I had/have a similar situation with a book that used Capitalized Words all over the place, all throughout. Trying to figure out what should be normal case and what shouldn't gave me several headaches.

**Comment by Survey0r** [comment]
OK, I'll move it up to the top of the CSS.

Also, I can squash various commits that are of the same type (but for separate sections) so that there aren't so many commits, if you'd like.

**Comment by Survey0r** [comment]
Actually, I have a proposal for how to go about this, since it seems like the < q > stuff is the main issue remaining.

1. Squash all the recent commits of the same type (such as the ones starting with "[Editorial] Replaced italics (used for quoting) with quotation marks...") so that the commit history doesn't have so many commits.
2. Remove all the < q > commits that don't result in merge issues.
3. Change manually (as a new commit) whatever needs to be changed from there, since it seems like some italics do need to be semanticated as < q > (such as the very end of chapter 1-4).

Sound good?

**Comment by vr8hub** [comment]
I've tested another 8-10 books, so I'm going to go ahead and submit my PR for the above issues. Here are a couple of additional issues I saw:
1. Whatever `create_draft` is doing to get rid of the `<head>` text, it's leaving blank lines, so every body.xhtml has `<head>` followed by a number of blank lines (I've seen as many as 32, from 43936), followed by `</head>`. It doesn't really matter since the producer is going to strip it anyway, so just mentioning it in case you care.
2. With pg id 11111, the producer text is still the old format, i.e. `Produced by George Smith`. But the table on the main page says `Etext produced by George Smith` and `HTML file produced by David Widger` on the next line. Somehow, `create_draft` got the text from the table, not from the html file, so it got both names but treated them as a single name. That is, e.g., colophon has `Etext produced by George Smith HTML file produced by David Widger` wrapped in a single `<b>`.

Otherwise, everything looks good, PG header/footer text always stripped, and names correct with the above exception. Actually, I found a "Scanned by John Doe with blah blah OCR professional software" in one of them, but that was an aberration (I've never seen that before), and it was on a book of a type we wouldn't produce, so I didn't worry about it.

**Comment by vr8hub** [comment]
Yes, per the discussion on the list, Alex said the end-of-chapter Bible verse quotes that lead into the next day's sermon that are just italics can be `<q>`s.

That sounds fine, just be sure and MAKE A BACKUP first. :)

**Comment by Survey0r** [comment]
OK, I've deleted what commits I can, and squashed other commits I can, without having merge conflicts. (Which were less than I would have liked, unfortunately.) 

I just added another commit fixing the < q > issues. I've left some < q > 's, however, as they seemed to be the case of using italics in place of quotations. Here are the < q > 's that have been left:

End of chapter Bible verse quotes that lead into the next sermon:
- Chapter 1-1, line 50
- Chapter 1-2, line 60
- Chapter 1-3, line 40
- Chapter 1-4, line 70
- Chapter 1-5, line 39
- Chapter 1-6, line 34
- Chapter 1-9, line 25
- Chapter 1-10, line 53
- Chapter 1-11, line 35
- Chapter 2-1, line 61
- Chapter 2-3, line 69
- Chapter 2-5, line 44
- Chapter 2-8, line 45
- Chapter 2-9, line 35
- Chapter 2-10, line 51
- Chapter 2-11, line 34
- Chapter 3-1, line 42
- Chapter 3-2, line 57
- Chapter 3-3, line 45
- Chapter 3-4, line 37
- Chapter 3-5, line 25
- Chapter 3-7, line 85
- Chapter 3-8, line 39
- Chapter 3-10, line 36
- Chapter 3-11, line 42

Use of italics in place of quotations:
- Chapter 1-12, line 18
- Chapter 2-6, line 50
- Chapter 2-7, line 17
- Chapter 3-3, line 44

Use of italics for internal thoughts:
- Chapter 2-10, line 23
- Chapter 3-10, line 30 (could also be a case of using italics in place of quotations)

Let me know if any of these need to still be fixed, and I'll fix them (and squash that commit into the latest commit so the italics adjustments are only one commit).

**Comment by vr8hub** [comment]
I searched for `<q>(.*?)</q>` and extracted them all. Anything less than a sentence is automatically suspect. To repeat from above: `<q>` is only used for _quotes_.

The "did not believe him" at the end of chapter 3-1 is not a quote.
The "the Truth, who is the Son, makes them free" at the end of chapter 3-4 is not a quote.
The "the Truth" at the end of chapter 3-3 is not a quote. Yes, those two words appear in the verse, but in the context of what he's saying at the end of the 3-3, he is not quoting that verse. Among the clues is the fact that "Truth" is capitalized (which it isn't in the verse)—he's calling Jesus the embodiment of Truth. He is _the Truth_.
The two "Father!"s are not quotes. Again, just because the word appears in the verse doesn't make it quote—they have exclamations (the verse doesn't), which is again, another hint.

All of those are emphasis.

I did not look at the rest, I'll leave that for you. The first rule is, if it's not a _quote_ (not a paraphrase), then it's not a `<q>`. The second rule is, `<q>` is used for _longer_ quotes; if it's just a word or two, then it's almost guaranteed it should be quoted, not italicized.

**Comment by Survey0r** [comment]
OK, that's fine, I'll switch those to emphasis.

With 2-9, line 35, it does seem to be in fact a longer quote. Does < q > remain there?

**Comment by vr8hub** [comment]
Yes, first because it is a _quote_. :)

**Comment by Survey0r** [comment]
OK, cool, glad I'm finally grasping it. :) I've left the < q > there.

Any other changes to make?

**Comment by vr8hub** [comment]
Lint is complaining about unused CSS.

**Comment by Survey0r** [comment]
My bad, I spaced out on that. I and my family have been preparing to move from one country to another, so my brain is fried.

I've removed the unused CSS selectors, ran clean and typogrify, and Lint isn't making any complaints any more.
